import { useState } from 'react'
import { Sparkles, Send, PanelRight, AppWindow, Maximize2, X } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Textarea } from '@/components/ui/textarea'
import { Badge } from '@/components/ui/badge'
import { ScrollArea } from '@/components/ui/scroll-area'
import { Sheet,SheetContent,SheetTitle,SheetDescription } from '@/components/ui/sheet'
import { Dialog,DialogContent,DialogTitle,DialogDescription } from '@/components/ui/dialog'
import { DropdownMenu,DropdownMenuTrigger,DropdownMenuContent,DropdownMenuRadioGroup,DropdownMenuRadioItem } from '@/components/ui/dropdown-menu'
import { IconButton } from './shared'
import { money, type RecordItem } from './domain'

export type AgentMode='sidebar'|'floating'|'full'
export default function Agent({open,setOpen,mode,setMode,record,records}:{open:boolean;setOpen:(o:boolean)=>void;mode:AgentMode;setMode:(m:AgentMode)=>void;record?:RecordItem;records:RecordItem[]}){
  const [input,setInput]=useState(''),[messages,setMessages]=useState<{role:string;text:string}[]>([])
  const summary=record?`${record.id}에서 ${record.pattern} 유형이 ${record.probability}% 확률로 탐지됨.\n근거 거래 ${record.count}건, 총 ${money(record.amount)} 확인됨. 계좌 간 관계와 거래 목적 확인 필요.`:`현재 미처리 업무 ${records.filter(r=>r.status!=='종결').length}건 중 고위험 ${records.filter(r=>r.risk==='고위험'&&r.status!=='종결').length}건 확인됨.\n위험 점수와 경과 기간을 함께 확인하여 우선 검토 필요.`
  const send=(text=input)=>{if(!text.trim())return;setMessages(p=>[...p,{role:'user',text},{role:'assistant',text:/근거|거래|흐름/.test(text)?`${record?record.id:'선택한 업무'}의 자금 흐름 및 거래 탭에서 송금 방향·거래 일시·금액 대조 필요. 연결 계좌의 반복 송금 여부와 실제 거래 목적 확인 필요.\n\n이 응답은 화면 검토용 예시이며 추가 분석은 수행되지 않음.`:/요약|우선/.test(text)?summary:`질문 확인됨. ${record?record.id+'의':'목록에서 조사할 항목의'} 탐지 근거와 처리 이력을 함께 확인할 필요가 있음.\n\n자유 질문에 대한 모델 분석은 연결되지 않은 상태임.`}]);setInput('')}
  const modes=[{value:'sidebar',label:'우측 사이드바',icon:PanelRight},{value:'floating',label:'플로팅 패널',icon:AppWindow},{value:'full',label:'전체화면',icon:Maximize2}] as const
  const activeMode=modes.find(i=>i.value===mode)!
  const header=<div className="flex items-center justify-between gap-2 border-b px-4 py-3"><div className="flex items-center gap-2 text-sm font-semibold"><Sparkles className="size-4"/>조사 도우미</div><div className="flex gap-0.5"><DropdownMenu><DropdownMenuTrigger asChild><Button variant="ghost" size="sm" className="h-8 text-xs" aria-label={`표시 방식: ${activeMode.label}`}><activeMode.icon className="size-3.5"/>{activeMode.label}</Button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuRadioGroup value={mode} onValueChange={v=>setMode(v as AgentMode)}>{modes.map(i=><DropdownMenuRadioItem key={i.value} value={i.value}><i.icon className="size-3.5"/>{i.label}</DropdownMenuRadioItem>)}</DropdownMenuRadioGroup></DropdownMenuContent></DropdownMenu><IconButton label="도우미 닫기" className="size-8" onClick={()=>setOpen(false)}><X className="size-4"/></IconButton></div></div>
  const body=<div className="flex flex-col h-full min-h-0">{header}<div className="flex gap-2 items-center px-4 py-3 text-[11px] text-muted-foreground border-b"><Badge variant="outline" className="text-[10px]">예시 응답</Badge>{record?.id??'대시보드 · 오늘 요약'}</div><ScrollArea className="flex-1 min-h-0"><div className="p-4 space-y-5"><div className="space-y-3"><div className="size-7 rounded-md border grid place-items-center"><Sparkles className="size-3.5"/></div><p className="text-sm leading-7 whitespace-pre-wrap">{summary}</p><div className="flex flex-wrap gap-2">{['주요 근거 확인','검토 우선순위 요약'].map(q=><Button key={q} variant="outline" size="sm" className="text-xs" onClick={()=>send(q)}>{q}</Button>)}</div></div>{messages.map((m,i)=><div key={i} className={m.role==='user'?'ml-6 bg-muted rounded-lg p-3 text-sm':'text-sm leading-7 py-2 whitespace-pre-wrap'}>{m.text}</div>)}</div></ScrollArea><form className="p-4 border-t" onSubmit={e=>{e.preventDefault();send()}}><div className="relative"><Textarea aria-label="도우미에게 질문" placeholder="현재 조사에 대해 질문하세요" className="min-h-24 resize-none pr-12 text-xs" value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();send()}}}/><Button size="icon" className="absolute bottom-2 right-2 size-7" disabled={!input.trim()} aria-label="질문 보내기"><Send className="size-3.5"/></Button></div><p className="text-[10px] text-muted-foreground mt-2 text-center">화면 검토용 예시 · 실제 모델·외부 전송 없음</p></form></div>
  return <>{!open&&<Button aria-label="조사 도우미 열기" className="fixed bottom-6 right-6 z-40 rounded-full size-12 shadow-lg" size="icon" onClick={()=>setOpen(true)}><Sparkles className="size-5"/></Button>}<Sheet modal={false} open={open&&mode==='sidebar'} onOpenChange={setOpen}><SheetContent showCloseButton={false} className="w-[380px]! max-w-[90vw]! p-0 gap-0" onInteractOutside={e=>e.preventDefault()} onOpenAutoFocus={e=>e.preventDefault()}><SheetTitle className="sr-only">조사 도우미</SheetTitle><SheetDescription className="sr-only">현재 화면에 대한 예시 응답</SheetDescription>{body}</SheetContent></Sheet><Dialog modal={false} open={open&&mode!=='sidebar'} onOpenChange={setOpen}><DialogContent showCloseButton={false} className={mode==='full'?'w-[calc(100vw-32px)]! max-w-none! h-[calc(100vh-32px)] p-0 block':'left-auto! top-auto! translate-x-0! translate-y-0! right-6 bottom-6 w-[400px] max-w-[90vw]! h-[620px] max-h-[90vh] p-0 block'} onInteractOutside={e=>e.preventDefault()}><DialogTitle className="sr-only">조사 도우미</DialogTitle><DialogDescription className="sr-only">현재 화면에 대한 예시 응답</DialogDescription>{body}</DialogContent></Dialog></>
}
