import { useState } from 'react'
import { useMemoryState } from './memory'
import { ArrowLeft, Check, FileClock, Link2, Network, Save, ShieldCheck } from 'lucide-react'
import { toast } from 'sonner'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { Card,CardContent } from '@/components/ui/card'
import { Textarea } from '@/components/ui/textarea'
import { Label } from '@/components/ui/label'
import { Select,SelectContent,SelectItem,SelectTrigger,SelectValue } from '@/components/ui/select'
import { Table,TableHeader,TableBody,TableRow,TableHead,TableCell } from '@/components/ui/table'
import { Dialog,DialogContent,DialogTitle,DialogDescription,DialogHeader,DialogFooter } from '@/components/ui/dialog'
import { AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogHeader,AlertDialogFooter,AlertDialogCancel,AlertDialogAction } from '@/components/ui/alert-dialog'
import { type RecordItem, money, canClose, transactionsFor } from './domain'
import { UnderTabs, RiskBadge, PatternBadge, SectionTitle } from './shared'
import Graph from './Graph'

type Draft={text:string;verdict:string;at:string}
type Event={title:string;body:string;at:string;actor:string}
export default function Detail({record:r,records,user,onBack,onUpdate,onOpen}:{record:RecordItem;records:RecordItem[];user:string;onBack:()=>void;onUpdate:(r:RecordItem)=>void;onOpen:(r:RecordItem)=>void}){
  const [tab,setTab]=useState('overview'),[reason,setReason]=useMemoryState(`${r.id}:reason`,r.status==='종결'?'거래 목적 및 계좌 관계 대조 완료. 정상 거래로 판단함.':''),[verdict,setVerdict]=useMemoryState(`${r.id}:verdict`,'normal'),[confirm,setConfirm]=useState(false),[draftOpen,setDraftOpen]=useState(false),[drafts,setDrafts]=useMemoryState<Draft[]>(`${r.id}:drafts`,[]),[events,setEvents]=useMemoryState<Event[]>(`${r.id}:events`,[]),[linkOpen,setLinkOpen]=useState(false),[episode,setEpisode]=useState(''),[linked,setLinked]=useMemoryState<string|null>(`${r.id}:linked`,r.episodeId??null)
  const responsible=r.owner===user,closed=r.status==='종결',tx=transactionsFor(r)
  const event=(title:string,body:string)=>setEvents(p=>[{title,body,at:new Date().toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit'}),actor:user},...p])
  const save=()=>{setDrafts(p=>[{text:reason,verdict,at:new Date().toLocaleTimeString('ko-KR')},...p]);event('검토 의견 임시 저장','종결 전 검토 의견을 저장함');toast.success('현재 화면에 임시 저장했습니다.')}
  const finish=()=>{if(!canClose(user,r.owner,reason))return;onUpdate({...r,status:'종결'});event(`${verdict==='normal'?'정상':'의심'} 종결`,reason);setConfirm(false);toast.success(`${r.id}를 종결했습니다.`)}
  return <div className="space-y-5"><Button variant="ghost" size="sm" onClick={onBack} className="-ml-2 text-muted-foreground"><ArrowLeft className="size-3.5"/>{r.kind} 목록</Button><div className="flex items-start justify-between gap-4"><div><div className="flex items-center gap-2 mb-2"><span className="font-mono text-xs text-muted-foreground">{r.id}</span><Badge variant="outline" className="text-[10px] font-normal">{r.status}</Badge></div><h1 className="text-xl font-semibold tracking-tight">{r.title}</h1><div className="flex items-center gap-3 mt-3"><RiskBadge risk={r.risk} score={r.score}/><PatternBadge pattern={r.pattern} probability={r.probability}/><span className="text-xs text-muted-foreground">담당 {r.owner} · {r.date} 탐지</span></div></div><div className="flex items-center gap-2">{r.kind==='Alert'&&<Button size="sm" variant="outline" disabled={!responsible||closed} onClick={()=>setLinkOpen(true)}><Link2 className="size-3.5"/>{linked?'연결된 Episode':'Episode 연결'}</Button>}<Button size="sm" disabled={closed} onClick={()=>setTab('conclusion')}><ShieldCheck className="size-3.5"/>{closed?'종결됨':'검토 의견 작성'}</Button></div></div>
    {!responsible&&<p className="text-xs text-muted-foreground rounded-md border px-3 py-2">현재 {user} 계정으로 조회 중입니다. 최종 처리는 담당자 {r.owner}가 수행합니다.</p>}
    {linked&&<div className="flex gap-2 items-center border rounded-md p-3 text-xs"><Link2 className="size-3.5"/>연결된 Episode<Button variant="link" className="p-0 h-auto text-xs" onClick={()=>onOpen(records.find(x=>x.id===linked)!)}>{linked}</Button></div>}
    <UnderTabs value={tab} onChange={setTab} items={[{value:'overview',label:'개요'},{value:'graph',label:'자금 흐름'},{value:'transactions',label:`거래 ${tx.length}`},{value:'conclusion',label:'검토 의견'}]}/>
    {tab==='overview'&&<div className="space-y-5"><div className="grid grid-cols-3 gap-4">{[{label:'거래 금액',value:money(r.amount)},{label:'근거 거래',value:`${r.count}건`},{label:'경과 기간',value:r.age===0?'오늘':`${r.age}일`}].map(s=><Card key={s.label} className="shadow-none"><CardContent><p className="text-xs text-muted-foreground">{s.label}</p><p className="text-xl font-semibold tabular-nums mt-3">{s.value}</p></CardContent></Card>)}</div><div className="grid grid-cols-[1.4fr_1fr] gap-4"><Card className="shadow-none"><CardContent><SectionTitle title="탐지 근거" description="탐지 신호를 확인하고 실제 거래와 대조하세요."/><div className="space-y-5 text-sm"><div className="flex gap-3"><span className="text-muted-foreground font-mono text-xs pt-0.5">01</span><div><p className="font-medium">{r.title}</p><p className="text-xs text-muted-foreground leading-6 mt-1">연결 계좌 사이의 {r.count}건 거래가 탐지 범위에 포함됨. 거래 목적 및 계좌 간 관계 확인 필요.</p></div></div><div className="flex gap-3"><span className="text-muted-foreground font-mono text-xs pt-0.5">02</span><div><p className="font-medium">탐지 유형 {r.pattern} · 모델 확률 {r.probability}%</p><p className="text-xs text-muted-foreground leading-6 mt-1">위험 점수 {r.score}점과 모델 확률은 별도 지표임. 유형 확률만으로 의심 거래를 확정하지 않음.</p></div></div></div><Button variant="outline" className="mt-5 text-xs" size="sm" onClick={()=>setTab('graph')}><Network className="size-3.5"/>관계 그래프에서 확인</Button></CardContent></Card><Card className="shadow-none"><CardContent><SectionTitle title="조사 정보"/><dl className="grid grid-cols-[88px_1fr] gap-y-5 text-xs"><dt className="text-muted-foreground">조사 단위</dt><dd>{r.kind==='Alert'?'단일 탐지 신호':'연관 Alert 묶음'}</dd><dt className="text-muted-foreground">담당자</dt><dd>{r.owner}</dd><dt className="text-muted-foreground">현재 상태</dt><dd>{r.status}</dd><dt className="text-muted-foreground">탐지일</dt><dd>{r.date}</dd><dt className="text-muted-foreground">데이터 기준</dt><dd>화면 검토용 샘플</dd></dl></CardContent></Card></div>
      {r.kind==='Episode'&&<Card className="shadow-none"><CardContent><SectionTitle title="연관 Alert" description="이 조사 사건에 연결된 탐지 신호"/>{records.filter(x=>x.kind==='Alert'&&x.episodeId===r.id).slice(0,3).map(x=><div className="flex gap-4 items-center py-3 border-b last:border-0" key={x.id}><Button variant="link" className="h-auto p-0 text-xs font-mono" onClick={()=>onOpen(x)}>{x.id}</Button><PatternBadge pattern={x.pattern} probability={x.probability}/><span className="text-xs text-muted-foreground ml-auto">{x.status}</span></div>)}</CardContent></Card>}
      <Card className="shadow-none"><CardContent><SectionTitle title="처리 이력" description="담당자 · 변경 사유 · 시각"/><div className="divide-y">{[...events,{title:'검토 시작',body:'탐지 근거와 연결 거래를 확인함',at:'13:42',actor:r.owner},{title:'담당자 자동 배정',body:`${r.owner}에게 배정됨`,at:'13:38',actor:'시스템'},{title:`${r.kind} 생성`,body:`${r.pattern} ${r.probability}% 탐지`,at:'13:35',actor:'시스템'}].map((e,i)=><div key={i} className="flex gap-4 py-4"><span className="text-[11px] text-muted-foreground tabular-nums w-10">{e.at}</span><span className="size-1.5 rounded-full bg-muted-foreground mt-1.5"/><div className="flex-1 text-xs"><p>{e.title}<span className="text-muted-foreground ml-3">{e.actor}</span></p><p className="text-muted-foreground mt-1.5 leading-5 whitespace-pre-wrap">{e.body}</p></div></div>)}</div></CardContent></Card></div>}
    {tab==='graph'&&<><p className="text-xs text-muted-foreground">근거 거래와 주변 계좌의 연결 관계 · 계좌를 선택해 탐색 범위를 좁히세요.</p><Graph/></>}
    {tab==='transactions'&&<div className="border rounded-lg overflow-hidden"><Table><TableHeader><TableRow><TableHead>거래 ID</TableHead><TableHead>일시</TableHead><TableHead>송금 계좌</TableHead><TableHead>수취 계좌</TableHead><TableHead className="text-right">금액</TableHead></TableRow></TableHeader><TableBody>{tx.map(t=><TableRow key={t.id}><TableCell className="font-mono text-xs">{t.id}</TableCell><TableCell className="text-xs">{t.at}</TableCell><TableCell className="text-xs">{t.from}</TableCell><TableCell className="text-xs">{t.to}</TableCell><TableCell className="text-right text-xs tabular-nums">{money(t.amount)}</TableCell></TableRow>)}</TableBody></Table></div>}
    {tab==='conclusion'&&<Card className="shadow-none max-w-4xl"><CardContent className="space-y-6"><SectionTitle title={closed?'종결된 검토':'검토 의견'} description={closed?'이 화면에서 완료한 처리 결과입니다.':'근거를 작성하고 최종 판단을 확인하세요. 임시 저장은 종결 처리되지 않습니다.'}/><div className="space-y-2"><Label>최종 판단</Label><Select value={verdict} onValueChange={setVerdict} disabled={closed||!responsible}><SelectTrigger className="w-64"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="normal">정상 · 종결</SelectItem>{r.kind==='Episode'&&<SelectItem value="suspicious">의심 · 조사 종결</SelectItem>}</SelectContent></Select></div><div className="space-y-2"><Label htmlFor="reason">판단 근거 <span className="text-muted-foreground">(필수)</span></Label><Textarea id="reason" value={reason} onChange={e=>setReason(e.target.value)} disabled={closed||!responsible} className="min-h-52 text-sm leading-7" placeholder="확인한 거래, 계좌 간 관계, 정상 또는 의심 판단의 근거를 작성하세요."/><p className="text-xs text-muted-foreground">{r.kind==='Alert'?'의심 신호는 Episode에 연결해 조사를 이어갈 수 있습니다.':'최종 판단과 조사 근거가 처리 이력에 기록됩니다.'}</p></div><div className="flex items-center justify-end gap-2 border-t pt-5"><Button variant="ghost" size="sm" onClick={()=>setDraftOpen(true)}><FileClock className="size-3.5"/>저장본 목록 {drafts.length>0&&`(${drafts.length})`}</Button><Button variant="secondary" size="sm" disabled={!responsible||closed||!reason.trim()} onClick={save}><Save className="size-3.5"/>임시 저장</Button><Button size="sm" disabled={closed||!canClose(user,r.owner,reason)} onClick={()=>setConfirm(true)}><Check className="size-3.5"/>종결 확인</Button></div></CardContent></Card>}
    <AlertDialog open={confirm} onOpenChange={setConfirm}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>{r.kind}를 {verdict==='normal'?'정상':'의심'} 종결할까요?</AlertDialogTitle><AlertDialogDescription>{r.id}의 판단 근거와 담당자를 처리 이력에 남깁니다. 이 프로토타입의 현재 실행 중인 데이터에만 반영됩니다.</AlertDialogDescription></AlertDialogHeader><div className="max-h-44 overflow-auto bg-muted rounded-md p-3 text-sm whitespace-pre-wrap">{reason}</div><AlertDialogFooter><AlertDialogCancel>돌아가기</AlertDialogCancel><AlertDialogAction onClick={finish}>종결 확정</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
    <Dialog open={draftOpen} onOpenChange={setDraftOpen}><DialogContent><DialogHeader><DialogTitle>저장본 목록</DialogTitle><DialogDescription>현재 상세 화면에서 임시 저장한 의견입니다.</DialogDescription></DialogHeader>{drafts.length===0?<p className="text-sm text-muted-foreground py-6">아직 저장된 의견이 없습니다.</p>:drafts.map((d,i)=><div key={i} className="border rounded-md p-3"><div className="flex justify-between items-center text-xs"><span>{d.at}</span><Button size="sm" variant="outline" disabled={closed||!responsible} onClick={()=>{setReason(d.text);setVerdict(d.verdict);setDraftOpen(false);toast.success('저장본을 불러왔습니다.')}}>불러오기</Button></div><p className="text-xs text-muted-foreground mt-2 line-clamp-3">{d.text}</p></div>)}</DialogContent></Dialog>
    <Dialog open={linkOpen} onOpenChange={setLinkOpen}><DialogContent><DialogHeader><DialogTitle>Episode 연결</DialogTitle><DialogDescription>기존 조사 사건을 선택해 Alert를 연결합니다.</DialogDescription></DialogHeader><Select value={episode} onValueChange={setEpisode}><SelectTrigger className="w-full"><SelectValue placeholder="연결할 Episode 선택"/></SelectTrigger><SelectContent>{records.filter(x=>x.kind==='Episode'&&x.status!=='종결').map(x=><SelectItem key={x.id} value={x.id}>{x.id} · {x.pattern} {x.probability}%</SelectItem>)}</SelectContent></Select><DialogFooter><Button variant="outline" onClick={()=>setLinkOpen(false)}>취소</Button><Button disabled={!episode} onClick={()=>{setLinked(episode);onUpdate({...r,episodeId:episode});event('Episode 연결',`${episode}에 탐지 신호를 연결함`);setLinkOpen(false);toast.success('Episode에 연결했습니다.')}}>연결 확인</Button></DialogFooter></DialogContent></Dialog>
  </div>
}
