import { useEffect, useState, type CSSProperties } from 'react'
import { Radar, LayoutDashboard, ScanLine, FolderSearch, Bell, Settings as SettingsIcon, ArrowLeft, ArrowRight, ChevronRight, Search, Maximize2, Minimize2, CheckSquare2 } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Card,CardContent,CardHeader,CardTitle,CardDescription } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { Label } from '@/components/ui/label'
import { Input } from '@/components/ui/input'
import { Select,SelectTrigger,SelectContent,SelectItem,SelectValue } from '@/components/ui/select'
import { Avatar,AvatarFallback } from '@/components/ui/avatar'
import { Separator } from '@/components/ui/separator'
import { SidebarProvider,Sidebar,SidebarHeader,SidebarContent,SidebarFooter,SidebarGroup,SidebarGroupLabel,SidebarGroupContent,SidebarMenu,SidebarMenuItem,SidebarMenuButton,SidebarInset,SidebarTrigger } from '@/components/ui/sidebar'
import { Popover,PopoverContent,PopoverTrigger } from '@/components/ui/popover'
import { AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction } from '@/components/ui/alert-dialog'
import { records as fixtures, type RecordItem } from './domain'
import Lists,{type DataState} from './Lists'
import Dashboard from './Dashboard'
import Detail from './Detail'
import Agent,{type AgentMode} from './Agent'
import { Account,Settings,Notifications } from './UtilityPages'
import { IconButton } from './shared'
import LoginNetwork from './LoginNetwork'

type Page='dashboard'|'alerts'|'episodes'|'notifications'|'settings'|'account'
const pages={dashboard:'대시보드',alerts:'Alert',episodes:'Episode',notifications:'알림',settings:'설정',account:'계정'} as const
const mainNav=[{id:'dashboard',name:'대시보드',icon:LayoutDashboard},{id:'alerts',name:'Alert',icon:ScanLine},{id:'episodes',name:'Episode',icon:FolderSearch}] as const
const utilityNav=[{id:'notifications',name:'알림',icon:Bell},{id:'settings',name:'설정',icon:SettingsIcon}] as const
export default function App(){
  const [user,setUser]=useState<string|null>(null),[loginRole]=useState('오검토'),[page,setPage]=useState<Page>('dashboard'),[records,setRecords]=useState(fixtures),[selected,setSelected]=useState<string|null>(null),[logout,setLogout]=useState(false),[state,setState]=useState<DataState>('normal'),[agentOpen,setAgentOpen]=useState(true),[agentMode,setAgentMode]=useState<AgentMode>('sidebar'),[globalSearch,setGlobalSearch]=useState(''),[searchOpen,setSearchOpen]=useState(false),[listKey,setListKey]=useState(0),[isFullscreen,setIsFullscreen]=useState(false)
  const record=records.find(r=>r.id===selected),role=user==='오검토'?'L1 · 1차 검토':'L2 · 심층 조사',todo=records.filter(r=>r.owner===user&&r.status!=='종결').length
  const results=globalSearch.trim()?records.filter(r=>`${r.id} ${r.title} ${r.pattern}`.toLowerCase().includes(globalSearch.toLowerCase())).slice(0,6):[]
  const go=(p:Page)=>{setPage(p);setSelected(null);setState('normal');if(p==='alerts'||p==='episodes')setListKey(k=>k+1);window.scrollTo(0,0)}
  const openRecord=(r:RecordItem)=>{setPage(r.kind==='Alert'?'alerts':'episodes');setSelected(r.id);setAgentOpen(false);setSearchOpen(false);setGlobalSearch('');window.scrollTo(0,0)}
  const logoutNow=()=>{setUser(null);setLogout(false);setAgentOpen(false);setSelected(null);setPage('dashboard')}
  const fullscreen=()=>document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen()
  useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.key==='/'){e.preventDefault();setSearchOpen(true);requestAnimationFrame(()=>document.querySelector<HTMLInputElement>('[aria-label=\"전역 검색\"]')?.focus())}};const screen=()=>setIsFullscreen(Boolean(document.fullscreenElement));window.addEventListener('keydown',key);document.addEventListener('fullscreenchange',screen);return()=>{window.removeEventListener('keydown',key);document.removeEventListener('fullscreenchange',screen)}},[])
  if(!user)return <div className="min-h-screen grid grid-cols-[1fr_1fr] login-layout"><div className="relative overflow-hidden flex flex-col justify-between p-12 border-r bg-[#09090b] text-white"><LoginNetwork/><div className="absolute inset-0 bg-gradient-to-br from-black/10 via-black/20 to-black/70 pointer-events-none"/><div className="relative z-10 flex items-center gap-2.5 font-semibold tracking-tight"><Radar className="size-5"/>AML RADAR</div><div className="relative z-10 max-w-md"><Badge variant="outline" className="font-normal mb-7 border-white/25 text-white">자금세탁 의심 거래 조사</Badge><h1 className="text-4xl leading-[1.4] tracking-tight font-semibold">탐지 신호에서<br/>판단의 근거까지.</h1><p className="mt-6 text-sm text-white/60 leading-7">Alert를 검토하고, 연결된 거래를 추적하고,<br/>Episode 단위로 조사를 이어갑니다.</p></div><p className="relative z-10 text-[11px] text-white/45">AML RADAR · v14</p></div><div className="flex flex-col items-center justify-center p-8"><Card className="w-full max-w-[390px] shadow-none"><CardHeader><CardTitle className="text-2xl">로그인</CardTitle><CardDescription>금융감독원 업무 계정으로 로그인하세요.</CardDescription></CardHeader><CardContent className="space-y-4"><div className="space-y-2"><Label htmlFor="email">이메일</Label><Input id="email" type="email" defaultValue="reviewer@fss.or.kr" autoComplete="username"/></div><div className="space-y-2"><Label htmlFor="password">비밀번호</Label><Input id="password" type="password" defaultValue="amlradar" autoComplete="current-password"/></div><Button className="w-full h-11" onClick={()=>setUser(loginRole)}>로그인<ArrowRight className="size-4"/></Button><Button variant="link" className="w-full text-xs text-muted-foreground">비밀번호를 잊으셨나요?</Button></CardContent></Card></div></div>
  const headerBackLabel=record?`${record.kind} 목록`:null
  return <SidebarProvider style={{'--sidebar-width':'210px'} as CSSProperties}><Sidebar collapsible="icon"><SidebarHeader className="h-15 flex items-center justify-center p-2"><SidebarTrigger className="size-9"/></SidebarHeader><SidebarContent><SidebarGroup><SidebarGroupLabel className="text-[10px] text-muted-foreground tracking-wider">WORKSPACE</SidebarGroupLabel><SidebarGroupContent><SidebarMenu className="gap-1.5">{mainNav.map(n=><SidebarMenuItem key={n.id}><SidebarMenuButton isActive={page===n.id} tooltip={n.name} onClick={()=>go(n.id)} className="h-10 px-3"><n.icon className="size-4"/><span>{n.name}</span></SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu></SidebarGroupContent></SidebarGroup><SidebarGroup className="mt-auto"><SidebarGroupContent><SidebarMenu className="gap-1.5">{utilityNav.map(n=><SidebarMenuItem key={n.id}><SidebarMenuButton isActive={page===n.id} tooltip={n.name} onClick={()=>go(n.id)} className="h-10 px-3"><n.icon className="size-4"/><span>{n.name}</span>{n.id==='notifications'&&<Badge variant="secondary" className="ml-auto h-5 min-w-5 px-1.5 group-data-[collapsible=icon]:hidden">7</Badge>}</SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu></SidebarGroupContent></SidebarGroup></SidebarContent><SidebarFooter className="border-t p-2"><SidebarMenu><SidebarMenuItem><SidebarMenuButton isActive={page==='account'} tooltip="계정" onClick={()=>go('account')} className="h-12 px-2 bg-transparent!"><Avatar className={`size-8 ${page==='account'?'ring-2 ring-foreground':''}`}><AvatarFallback className="text-xs">{user[0]}</AvatarFallback></Avatar><div className="min-w-0 flex-1 text-left group-data-[collapsible=icon]:hidden"><p className="text-xs font-medium">{user}</p><p className="text-[10px] text-muted-foreground mt-0.5">{role}</p></div><ChevronRight className="size-3.5 group-data-[collapsible=icon]:hidden"/></SidebarMenuButton></SidebarMenuItem></SidebarMenu></SidebarFooter></Sidebar>
    <SidebarInset className={`min-w-0 transition-[margin] ${agentOpen&&agentMode==='sidebar'?'agent-sidebar-space':''}`}><header className="sticky top-0 z-40 bg-background h-15 shrink-0 border-b grid grid-cols-[1fr_minmax(280px,480px)_1fr] items-center gap-5 px-6"><div className="flex items-center min-w-0">{headerBackLabel?<Button variant="ghost" size="sm" className="-ml-2 h-8 text-xs" onClick={()=>setSelected(null)}><ArrowLeft className="size-3.5"/>{headerBackLabel}</Button>:<span className="text-xs font-semibold">{pages[page]}</span>}</div><Popover open={searchOpen} onOpenChange={setSearchOpen}><PopoverTrigger asChild><div className="relative"><Search className="absolute left-3 top-2.5 size-3.5 text-muted-foreground"/><Input aria-label="전역 검색" placeholder="Alert ID · Episode ID · 탐지 내용 검색" className="h-9 pl-9 pr-12 bg-muted/40" value={globalSearch} onFocus={()=>setSearchOpen(true)} onChange={e=>{setGlobalSearch(e.target.value);setSearchOpen(true)}} onKeyDown={e=>{if(e.key==='Enter'&&results[0])openRecord(results[0])}}/><kbd className="absolute right-2 top-2 rounded border px-1.5 py-0.5 text-[10px] text-muted-foreground">/</kbd></div></PopoverTrigger><PopoverContent className="w-[480px] p-2" onOpenAutoFocus={e=>e.preventDefault()}>{results.length?results.map(r=><Button key={r.id} variant="ghost" className="w-full h-auto justify-start p-3" onClick={()=>openRecord(r)}><span className="font-mono text-xs">{r.id}</span><span className="ml-3 text-xs text-muted-foreground truncate">{r.title}</span></Button>):<p className="text-xs text-muted-foreground p-4 text-center">검색어를 입력하세요.</p>}</PopoverContent></Popover><div className="justify-self-end flex items-center gap-1"><Button variant="ghost" size="sm" className="h-8 text-xs" onClick={()=>go(user==='오검토'?'alerts':'episodes')}><CheckSquare2 className="size-3.5"/>할 일 <Badge variant="secondary" className="ml-1 h-5 min-w-5 px-1.5">{todo}</Badge></Button><Badge variant="outline" className="h-7 font-normal">{role}</Badge><Button variant="ghost" size="sm" className="h-8 gap-1.5" aria-label={isFullscreen?'전체화면 취소 · F11':'전체화면 · F11'} onClick={fullscreen}>{isFullscreen?<Minimize2 className="size-4"/>:<Maximize2 className="size-4"/>}<kbd className="text-[10px] text-muted-foreground">F11</kbd></Button></div></header><main className="px-7 py-7 pb-8 min-w-0">{record?<Detail key={record.id} record={record} records={records} user={user} onUpdate={r=>setRecords(p=>p.map(x=>x.id===r.id?r:x))} onOpen={openRecord}/>:page==='dashboard'?<Dashboard records={records} user={user} onOpen={openRecord}/>:page==='alerts'||page==='episodes'?<Lists key={`${page}-${listKey}`} kind={page==='alerts'?'Alert':'Episode'} records={records} user={user} onOpen={openRecord} state={state} setState={setState}/>:page==='account'?<Account user={user} onLogout={logoutNow}/>:page==='settings'?<Settings user={user}/>:<Notifications records={records} onOpen={openRecord}/>}</main></SidebarInset>
    <Agent open={agentOpen} setOpen={setAgentOpen} mode={agentMode} setMode={setAgentMode} record={record} records={records}/><AlertDialog open={logout} onOpenChange={setLogout}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>로그아웃할까요?</AlertDialogTitle><AlertDialogDescription>로그인 화면에서 다른 조사자 계정으로 시연을 이어갈 수 있습니다.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>취소</AlertDialogCancel><AlertDialogAction onClick={logoutNow}>로그아웃</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
  </SidebarProvider>
}
