import { useState } from 'react'
import { ArrowRight, Clock3, ShieldCheck, ListChecks } from 'lucide-react'
import { Area, AreaChart, CartesianGrid, XAxis } from 'recharts'
import { Card, CardContent } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Progress } from '@/components/ui/progress'
import { ChartContainer, ChartTooltip, ChartTooltipContent } from '@/components/ui/chart'
import { UnderTabs, SectionTitle, RiskBadge, PatternBadge } from './shared'
import { type RecordItem, patterns } from './domain'

export default function Dashboard({records,user,onOpen}:{records:RecordItem[];user:string;onOpen:(r:RecordItem)=>void}){
  const [scope,setScope]=useState('personal')
  const mine=records.filter(r=>r.owner===user&&r.status!=='종결'),all=records.filter(r=>r.status!=='종결'),queue=(scope==='personal'?mine:all).slice().sort((a,b)=>b.score-a.score).slice(0,5)
  const stats=scope==='personal'?[{label:'내 담당 미처리',value:mine.length,sub:'검토·조사가 필요한 업무',icon:ListChecks},{label:'3일 이상 경과',value:mine.filter(r=>r.age>=3).length,sub:'우선 처리가 필요한 업무',icon:Clock3},{label:'내 종결',value:records.filter(r=>r.owner===user&&r.status==='종결').length,sub:'현재 조회 범위 기준',icon:ShieldCheck}]:[{label:'미처리 Alert',value:all.filter(r=>r.kind==='Alert').length,sub:'기관 전체 탐지 신호',icon:ListChecks},{label:'진행 중 Episode',value:all.filter(r=>r.kind==='Episode').length,sub:'기관 전체 조사 사건',icon:Clock3},{label:'고위험 미처리',value:all.filter(r=>r.risk==='고위험').length,sub:'Alert · Episode 합계',icon:ShieldCheck}]
  const trend=Array.from({length:7},(_,i)=>{const day=`2026-09-${10+i}`;return {date:`9/${10+i}`,Alert:records.filter(r=>r.kind==='Alert'&&r.date===day).length,Episode:records.filter(r=>r.kind==='Episode'&&r.date===day).length}})
  return <div className="space-y-6"><UnderTabs value={scope} onChange={setScope} items={[{value:'personal',label:'내 담당'},{value:'institution',label:'기관 전체'}]}/><div className="grid grid-cols-3 gap-4">{stats.map(s=><Card key={s.label} className="shadow-none"><CardContent className="pt-1"><div className="flex items-center justify-between text-xs text-muted-foreground">{s.label}</div><div className="text-3xl font-semibold tracking-tight mt-4 tabular-nums">{s.value}<span className="text-sm font-normal ml-1.5 text-muted-foreground">건</span></div><p className="text-[11px] text-muted-foreground mt-2">{s.sub}</p></CardContent></Card>)}</div>
    {scope==='institution'&&<div className="grid grid-cols-2 gap-4"><Card className="shadow-none"><CardContent><SectionTitle title="탐지 추이" description="최근 7일 · 탐지일 기준"/><ChartContainer config={{Alert:{label:'Alert',color:'var(--chart-1)'},Episode:{label:'Episode',color:'var(--chart-2)'}}} className="h-[185px] w-full"><AreaChart data={trend} margin={{left:5,right:5,top:12}}><CartesianGrid vertical={false} strokeDasharray="3 3"/><XAxis dataKey="date" axisLine={false} tickLine={false} tickMargin={10}/><ChartTooltip content={<ChartTooltipContent/>}/><Area type="monotone" dataKey="Alert" stroke="var(--color-Alert)" fill="var(--color-Alert)" fillOpacity={.12} strokeWidth={2}/><Area type="monotone" dataKey="Episode" stroke="var(--color-Episode)" fill="var(--color-Episode)" fillOpacity={.06} strokeWidth={2}/></AreaChart></ChartContainer></CardContent></Card><Card className="shadow-none"><CardContent><SectionTitle title="유형별 미처리 Alert" description="유형 확률은 개별 Alert에서 확인"/><div className="space-y-6 pt-1">{patterns.map(p=>{const n=all.filter(r=>r.kind==='Alert'&&r.pattern===p).length;return <div className="grid grid-cols-[76px_28px_1fr] gap-3 items-center" key={p}><span className="text-xs font-mono">{p}</span><span className="text-xs text-right tabular-nums">{n}</span><Progress value={n/Math.max(...patterns.map(x=>all.filter(r=>r.kind==='Alert'&&r.pattern===x).length))*100} className="h-2"/></div>})}</div></CardContent></Card></div>}
    <Card className="shadow-none"><CardContent><SectionTitle title={scope==='personal'?'먼저 확인할 업무':'기관 우선 처리 업무'} description="위험 점수 높은 순 · 종결 건 제외"/><div className="divide-y">{queue.map(r=><div key={r.id} className="grid grid-cols-[1fr_auto] items-center gap-4 py-4 first:pt-0 last:pb-0 cursor-pointer hover:bg-muted/40 rounded-md px-2" onClick={()=>onOpen(r)}><div className="min-w-0"><Button variant="link" className="p-0 h-auto text-xs font-mono" onClick={()=>onOpen(r)}>{r.id}</Button><p className="text-sm mt-1.5 truncate">{r.title}</p><div className="flex gap-2 mt-2 items-center"><PatternBadge pattern={r.pattern} probability={r.probability}/><span className="text-[11px] text-muted-foreground">{r.owner} · {r.age===0?'오늘 탐지':`${r.age}일 경과`}</span></div></div><RiskBadge risk={r.risk} score={r.score}/></div>)}</div></CardContent></Card>
    {scope==='personal'&&<Card className="shadow-none"><CardContent><SectionTitle title="최근 내 활동" description="현재 조회 범위에서 최근 처리한 업무"/>{records.filter(r=>r.owner===user).slice(0,3).map((r,i)=><div key={r.id} className="flex gap-4 items-center border-b last:border-0 py-3 text-xs"><span className="text-muted-foreground tabular-nums w-10">{14-i}:24</span><span className="size-1.5 rounded-full bg-muted-foreground"/><span className="flex-1">{r.id} <span className="text-muted-foreground ml-2">{r.status==='종결'?'검토 종결':'검토 시작'}</span></span><Button variant="ghost" size="sm" className="h-7 text-xs" onClick={()=>onOpen(r)}>열기<ArrowRight className="size-3"/></Button></div>)}</CardContent></Card>}
  </div>
}
