import { useState } from 'react'
import type { DateRange } from 'react-day-picker'
import { ArrowDownUp, ArrowRight, ChevronLeft, ChevronRight, Download, ListFilter, RefreshCw, Search, TriangleAlert, Inbox } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Table,TableHeader,TableBody,TableRow,TableHead,TableCell } from '@/components/ui/table'
import { Select,SelectTrigger,SelectContent,SelectItem,SelectValue } from '@/components/ui/select'
import { Popover,PopoverTrigger,PopoverContent } from '@/components/ui/popover'
import { Label } from '@/components/ui/label'
import { Badge } from '@/components/ui/badge'
import { Skeleton } from '@/components/ui/skeleton'
import { matches, money, patterns, type RecordItem, type Filter, type Kind } from './domain'
import { PatternBadge, RiskBadge, DateRangeButton, FilterChip } from './shared'

export type DataState='normal'|'loading'|'empty'|'error'|'stale'
type SortKey='id'|'score'|'pattern'|'amount'|'count'|'owner'|'status'|'date'
function SortableHead({label,value,sortKey,direction,onSort,className}:{label:string;value:SortKey;sortKey:SortKey;direction:'asc'|'desc';onSort:(key:SortKey)=>void;className?:string}){return <TableHead className={className}><Button variant="ghost" size="sm" className="h-8 -ml-3 px-3 text-xs font-medium" onClick={()=>onSort(value)} aria-label={`${label} 정렬`}>{label}<ArrowDownUp className={`size-3 ${sortKey===value?'opacity-100':'opacity-45'}`}/><span className="sr-only">{sortKey===value?direction:''}</span></Button></TableHead>}

export function RecordTable({rows,onOpen}:{rows:RecordItem[];onOpen:(r:RecordItem)=>void}){
  const [sortKey,setSortKey]=useState<SortKey>('score'),[direction,setDirection]=useState<'asc'|'desc'>('desc')
  const onSort=(key:SortKey)=>{if(key===sortKey)setDirection(d=>d==='asc'?'desc':'asc');else{setSortKey(key);setDirection(key==='id'||key==='pattern'||key==='owner'||key==='status'?'asc':'desc')}}
  const sorted=rows.slice().sort((a,b)=>{const av=a[sortKey],bv=b[sortKey],comparison=typeof av==='number'&&typeof bv==='number'?av-bv:String(av).localeCompare(String(bv),'ko');return direction==='asc'?comparison:-comparison})
  return <Table><TableHeader><TableRow><SortableHead label="ID / 탐지 내용" value="id" sortKey={sortKey} direction={direction} onSort={onSort} className="pl-4"/><SortableHead label="위험도" value="score" sortKey={sortKey} direction={direction} onSort={onSort}/><SortableHead label="탐지 유형 · 확률" value="pattern" sortKey={sortKey} direction={direction} onSort={onSort}/><SortableHead label="거래 금액" value="amount" sortKey={sortKey} direction={direction} onSort={onSort} className="text-right"/><SortableHead label="거래" value="count" sortKey={sortKey} direction={direction} onSort={onSort} className="text-right"/><SortableHead label="담당자" value="owner" sortKey={sortKey} direction={direction} onSort={onSort}/><SortableHead label="상태" value="status" sortKey={sortKey} direction={direction} onSort={onSort}/><SortableHead label="탐지일" value="date" sortKey={sortKey} direction={direction} onSort={onSort}/><TableHead className="w-8"><span className="sr-only">열기</span></TableHead></TableRow></TableHeader><TableBody>{sorted.map(r=><TableRow key={r.id} className="cursor-pointer group" onClick={()=>onOpen(r)}><TableCell className="pl-4"><Button variant="link" className="p-0 h-auto text-xs font-mono justify-start" onClick={e=>{e.stopPropagation();onOpen(r)}}>{r.id}</Button><p className="text-[11px] text-muted-foreground mt-1">{r.title}</p></TableCell><TableCell><RiskBadge risk={r.risk} score={r.score}/></TableCell><TableCell><PatternBadge pattern={r.pattern} probability={r.probability}/></TableCell><TableCell className="text-right tabular-nums text-xs">{money(r.amount)}</TableCell><TableCell className="text-right text-xs tabular-nums">{r.count}건</TableCell><TableCell className="text-xs">{r.owner}</TableCell><TableCell><Badge variant={r.status==='신규'?'secondary':'outline'} className="font-normal text-[11px]">{r.status}</Badge></TableCell><TableCell className="text-xs text-muted-foreground tabular-nums">{r.date.slice(5)}<p className={r.age>=3?'text-amber-400 mt-1':'mt-1'}>{r.age===0?'오늘':`${r.age}일 경과`}</p></TableCell><TableCell><ArrowRight className="size-3.5 text-muted-foreground opacity-0 group-hover:opacity-100"/></TableCell></TableRow>)}</TableBody></Table>
}

export default function Lists({kind,records,user,onOpen,state,setState,initialFilters=[]}:{kind:Kind;records:RecordItem[];user:string;onOpen:(r:RecordItem)=>void;state:DataState;setState:(s:DataState)=>void;initialFilters?:Filter[]}){
  const [query,setQuery]=useState(''),[filters,setFilters]=useState<Filter[]>(initialFilters),[field,setField]=useState<Filter['field']>('risk'),[value,setValue]=useState('고위험'),[filterOpen,setFilterOpen]=useState(false)
  const [range,setRange]=useState<DateRange>(),[page,setPage]=useState(0)
  const base=records.filter(r=>r.kind===kind),result=state==='empty'?[]:base.filter(r=>matches(r,filters,query,range?.from,range?.to))
  const count=8,pages=Math.max(1,Math.ceil(result.length/count)),current=Math.min(page,pages-1)
  const fields:Record<Filter['field'],string[]>={risk:['고위험','중위험','저위험'],owner:['내 담당',...new Set(base.map(r=>r.owner).filter(x=>x!==user))],status:['신규',kind==='Alert'?'검토 중':'조사 중','종결'],pattern:patterns,age:['1','3','7','14','30']}
  const fieldNames={risk:'위험도',owner:'담당자',status:'처리 상태',pattern:'탐지 유형',age:'경과일'}
  const normalized=(f:Filter):Filter=>f.field==='owner'&&f.value==='내 담당'?{field:'owner',value:user}:f
  const chipLabel=(f:Filter)=>f.field==='owner'&&f.value===user?'담당자: 내 담당':f.field==='age'?`경과일: ${f.value}일 이상`:`${fieldNames[f.field]}: ${f.value}`
  const reset=()=>{setQuery('');setFilters([]);setRange(undefined);setPage(0);setState('normal')}
  const setPreset=(preset:'mine'|'risk'|'age'|'all')=>{setFilters(preset==='mine'?[{field:'owner',value:user}]:preset==='risk'?[{field:'risk',value:'고위험'}]:preset==='age'?[{field:'age',value:'3'}]:[]);setPage(0);setFilterOpen(false)}
  function download(){const csv='\uFEFF'+['ID,위험도,탐지 유형,확률,금액,상태',...result.map(r=>`${r.id},${r.risk},${r.pattern},${r.probability}%,${r.amount},${r.status}`)].join('\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8;'}));const a=document.createElement('a');a.href=url;a.download=`${kind}-목록.csv`;a.click();URL.revokeObjectURL(url)}
  return <div className="space-y-5"><div className="flex flex-wrap items-center gap-2"><div className="relative w-64 mr-1"><Search className="size-4 absolute left-3 top-2.5 text-muted-foreground"/><Input aria-label={`${kind} 검색`} placeholder="ID, 탐지 내용, 담당자 검색" value={query} onChange={e=>{setQuery(e.target.value);setPage(0)}} className="pl-9 h-9 text-xs"/></div><DateRangeButton value={range} onChange={r=>{setRange(r);setPage(0)}}/><Popover open={filterOpen} onOpenChange={setFilterOpen}><PopoverTrigger asChild><Button variant="outline" size="sm"><ListFilter className="size-3.5"/>필터{filters.length>0&&<Badge className="ml-1 h-5 min-w-5 px-1.5">{filters.length}</Badge>}</Button></PopoverTrigger><PopoverContent align="start" className="w-72 space-y-4"><div><p className="text-sm font-semibold">필터</p><p className="text-xs text-muted-foreground mt-1">조건은 AND로 적용됩니다.</p></div><div className="border-t pt-4 space-y-3"><Label>조건 추가</Label><Select value={field} onValueChange={v=>{setField(v as Filter['field']);setValue(fields[v as Filter['field']][0])}}><SelectTrigger className="w-full"><SelectValue/></SelectTrigger><SelectContent>{Object.entries(fieldNames).map(([k,v])=><SelectItem key={k} value={k}>{v}</SelectItem>)}</SelectContent></Select><Select value={value} onValueChange={setValue}><SelectTrigger className="w-full"><SelectValue/></SelectTrigger><SelectContent>{fields[field].map(v=><SelectItem key={v} value={v}>{field==='age'?`${v}일 이상`:v}</SelectItem>)}</SelectContent></Select><Button className="w-full" size="sm" onClick={()=>{const f=normalized({field,value});setFilters(p=>p.some(x=>x.field===f.field&&x.value===f.value)?p:[...p,f]);setPage(0);setFilterOpen(false)}}>조건 적용</Button></div></PopoverContent></Popover><Button variant="ghost" size="sm" className="ml-auto" onClick={download}><Download className="size-3.5"/>다운로드</Button></div>
    {(filters.length>0||range?.from)&&<div className="flex flex-wrap gap-2 items-center">{filters.map((f,i)=><FilterChip key={`${f.field}-${f.value}`} onRemove={()=>setFilters(p=>p.filter((_,j)=>j!==i))}>{chipLabel(f)}</FilterChip>)}<Button variant="ghost" size="sm" className="h-7 text-xs text-muted-foreground" onClick={reset}>모든 조건 지우기</Button></div>}
    <div className="space-y-3"><div className="flex items-center justify-between"><p className="text-xs text-muted-foreground">총 <span className="font-semibold text-foreground tabular-nums">{result.length}</span>건</p></div>
      {state==='stale'&&<div role="alert" className="flex items-center gap-3 rounded-md border border-amber-400/30 bg-amber-400/5 px-3 py-2"><TriangleAlert className="size-4 text-amber-400 shrink-0"/><div className="text-xs flex-1">재조회 실패 · 마지막 정상 결과를 유지합니다<span className="block text-[10px] text-muted-foreground mt-0.5">마지막 성공 14:32 · 요청 REQ-DEMO-016</span></div><Button size="sm" variant="outline" onClick={()=>setState('normal')}><RefreshCw className="size-3"/>다시 시도</Button></div>}
      <div className="border rounded-lg overflow-hidden">{state==='loading'?<div className="p-4 space-y-6" aria-label="목록 불러오는 중">{Array.from({length:8},(_,i)=><Skeleton key={i} className="h-8 w-full"/>)}</div>:state==='error'?<div className="py-20 text-center"><TriangleAlert className="size-6 mx-auto mb-4 text-muted-foreground"/><p className="text-sm">목록을 불러오지 못했습니다.</p><p className="text-xs text-muted-foreground mt-2 mb-4">잠시 후 다시 시도해 주세요.</p><Button size="sm" variant="outline" onClick={()=>setState('normal')}>다시 시도</Button></div>:result.length?<RecordTable rows={result.slice(current*count,(current+1)*count)} onOpen={onOpen}/>:<div className="py-20 text-center"><Inbox className="size-7 mx-auto mb-4 text-muted-foreground"/><p className="text-sm">조건에 맞는 {kind}가 없습니다.</p><p className="text-xs text-muted-foreground mt-2 mb-4">검색어와 필터를 확인하세요.</p><Button size="sm" variant="outline" onClick={reset}>전체 목록 보기</Button></div>}</div>
      <div className="flex items-center justify-between text-xs text-muted-foreground"><span>{result.length?`${current*count+1}–${Math.min((current+1)*count,result.length)}`:'0'} / {result.length}건</span><div className="flex items-center gap-3"><Button variant="outline" size="icon" className="size-7" disabled={current===0} aria-label="이전 페이지" onClick={()=>setPage(current-1)}><ChevronLeft className="size-3.5"/></Button><span>{current+1} / {pages}</span><Button variant="outline" size="icon" className="size-7" disabled={current>=pages-1} aria-label="다음 페이지" onClick={()=>setPage(current+1)}><ChevronRight className="size-3.5"/></Button></div></div>
    </div></div>
}
