import { useRef, useState } from 'react'
import type { DateRange } from 'react-day-picker'
import { useTheme } from 'next-themes'
import { Camera, Monitor, Laptop, Bell, Check, Sun, Moon, LaptopMinimal, RotateCcw, Search, ListFilter, MoreHorizontal } from 'lucide-react'
import { toast } from 'sonner'
import { Card,CardContent } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Avatar,AvatarImage,AvatarFallback } from '@/components/ui/avatar'
import { Badge } from '@/components/ui/badge'
import { Label } from '@/components/ui/label'
import { Checkbox } from '@/components/ui/checkbox'
import { Input } from '@/components/ui/input'
import { Select,SelectContent,SelectItem,SelectTrigger,SelectValue } from '@/components/ui/select'
import { RadioGroup,RadioGroupItem } from '@/components/ui/radio-group'
import { DropdownMenu,DropdownMenuContent,DropdownMenuItem,DropdownMenuTrigger } from '@/components/ui/dropdown-menu'
import { DateRangeButton,SectionTitle, PatternBadge } from './shared'
import type { RecordItem } from './domain'

export function Account({user,onLogout}:{user:string;onLogout:()=>void}){
  const [sessions,setSessions]=useState(['current','other-1','other-2']),[picture,setPicture]=useState(''); const file=useRef<HTMLInputElement>(null)
  return <div className="grid gap-5 xl:grid-cols-2"><Card className="shadow-none"><CardContent><SectionTitle title="프로필"/><div className="flex items-center gap-5 mb-8"><Avatar className="size-18"><AvatarImage src={picture}/><AvatarFallback className="text-xl">{user[0]}</AvatarFallback></Avatar><div><p className="font-semibold">{user}</p><Button variant="outline" size="sm" className="mt-2 text-xs" onClick={()=>file.current?.click()}><Camera className="size-3.5"/>이미지 변경</Button><input hidden ref={file} type="file" accept="image/*" onChange={e=>{const f=e.target.files?.[0];if(f)setPicture(URL.createObjectURL(f))}}/></div></div><dl className="grid grid-cols-2 gap-6 text-sm">{[['이름',user],['소속','금융감독원'],['역할',user==='오검토'?'L1 · 1차 검토':'L2 · 심층 조사'],['계정','업무 계정'],['이메일','reviewer@fss.or.kr'],['가입일','2026. 08. 05']].map(([k,v])=><div key={k}><dt className="text-xs text-muted-foreground mb-2">{k}</dt><dd>{v}</dd></div>)}</dl></CardContent></Card><Card className="shadow-none"><CardContent><SectionTitle title="세션 관리" description="현재 계정으로 로그인한 기기" action={<Button variant="outline" size="sm" onClick={()=>setSessions(['current'])}>다른 세션 모두 로그아웃</Button>}/><div className="space-y-3">{sessions.map((id,i)=><div key={id} className="flex items-center gap-4 rounded-lg border p-4"><div className="size-10 rounded-md border grid place-items-center">{i===0?<Monitor className="size-4"/>:<Laptop className="size-4"/>}</div><div className="flex-1"><p className="text-sm">Chrome · macOS {id==='current'&&<Badge variant="secondary" className="ml-2">현재</Badge>}</p><p className="text-xs text-muted-foreground mt-1">대한민국 서울 · {i===0?'방금 활동':'오늘 09:14'}</p></div><Button variant="ghost" size="sm" onClick={()=>id==='current'?onLogout():setSessions(p=>p.filter(x=>x!==id))}>로그아웃</Button></div>)}</div></CardContent></Card></div>
}

export function Settings({user}:{user:string}){
  const {theme,setTheme}=useTheme(); const [rows,setRows]=useState('20'),[sort,setSort]=useState('risk'),[alerts,setAlerts]=useState(['assigned','linked','comment','result'])
  const reset=()=>{setRows('20');setSort('risk');setAlerts(['assigned','linked','comment','result']);setTheme('system');toast.success('설정을 초기화했습니다.')}
  const choices=user==='오검토'?[['assigned','내 Alert 배정'],['linked','Alert의 Episode 연결'],['comment','새 의견'],['result','Batch 결과']]:[['assigned','내 Episode 배정'],['linked','Episode에 Alert 연결'],['comment','새 의견'],['result','종결 결과']]
  return <div className="space-y-5"><div className="flex justify-end"><Button size="sm" variant="outline" onClick={reset}><RotateCcw className="size-3.5"/>설정 초기화</Button></div><div className="grid gap-4 xl:grid-cols-4 sm:grid-cols-2"><Card className="shadow-none"><CardContent><SectionTitle title="일반"/><div className="space-y-5"><div className="space-y-2"><Label>시간대</Label><Select defaultValue="seoul"><SelectTrigger className="w-full"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="seoul">Asia/Seoul (UTC+9)</SelectItem></SelectContent></Select></div><div className="space-y-2"><Label>날짜 형식</Label><Select defaultValue="iso"><SelectTrigger className="w-full"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="iso">YYYY-MM-DD</SelectItem><SelectItem value="dot">YYYY. MM. DD</SelectItem></SelectContent></Select></div></div></CardContent></Card><Card className="shadow-none"><CardContent><SectionTitle title="목록"/><div className="space-y-5"><div className="space-y-2"><Label>페이지당 행</Label><Select value={rows} onValueChange={setRows}><SelectTrigger className="w-full"><SelectValue/></SelectTrigger><SelectContent>{['20','50','100'].map(v=><SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select></div><div className="space-y-2"><Label>기본 정렬</Label><Select value={sort} onValueChange={setSort}><SelectTrigger className="w-full"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="risk">위험도 높은 순</SelectItem><SelectItem value="recent">최근 탐지 순</SelectItem></SelectContent></Select></div></div></CardContent></Card><Card className="shadow-none"><CardContent><SectionTitle title="알림" description="인앱 수신 항목"/><div className="space-y-4">{choices.map(([id,label])=><Label key={id} className="flex items-center gap-3 font-normal"><Checkbox checked={alerts.includes(id)} onCheckedChange={v=>setAlerts(p=>v?[...new Set([...p,id])]:p.filter(x=>x!==id))}/>{label}</Label>)}</div></CardContent></Card><Card className="shadow-none"><CardContent><SectionTitle title="테마"/><RadioGroup value={theme??'system'} onValueChange={setTheme} className="space-y-3">{[{id:'system',label:'시스템 설정',icon:LaptopMinimal},{id:'light',label:'라이트 모드',icon:Sun},{id:'dark',label:'다크 모드',icon:Moon}].map(t=><Label key={t.id} htmlFor={`theme-${t.id}`} className="flex items-center gap-3 rounded-lg border p-3 font-normal cursor-pointer"><RadioGroupItem id={`theme-${t.id}`} value={t.id}/><t.icon className="size-4"/>{t.label}</Label>)}</RadioGroup></CardContent></Card></div></div>
}

export function Notifications({records,onOpen}:{records:RecordItem[];onOpen:(r:RecordItem)=>void}){
  const [read,setRead]=useState<string[]>([]),[query,setQuery]=useState(''),[unreadOnly,setUnreadOnly]=useState(false),[range,setRange]=useState<DateRange>()
  const iso=(d:Date)=>d.toLocaleDateString('sv-SE'),alerts=records.slice(0,7).filter(r=>`${r.id} ${r.title}`.toLowerCase().includes(query.toLowerCase())).filter(r=>!unreadOnly||!read.includes(r.id)).filter(r=>(!range?.from||r.date>=iso(range.from))&&(!range?.to||r.date<=iso(range.to)))
  return <div className="space-y-5"><div className="flex flex-wrap gap-2"><div className="relative w-72"><Search className="absolute left-3 top-2.5 size-4 text-muted-foreground"/><Input className="pl-9 h-9" placeholder="알림 내용, Alert·Episode ID 검색" value={query} onChange={e=>setQuery(e.target.value)}/></div><DateRangeButton value={range} onChange={setRange}/><Button variant={unreadOnly?'secondary':'outline'} size="sm" onClick={()=>setUnreadOnly(v=>!v)}><ListFilter className="size-3.5"/>읽지 않음</Button><Button variant="ghost" size="sm" className="ml-auto" onClick={()=>setRead(records.map(r=>r.id))}><Check className="size-3.5"/>모두 읽음</Button></div><Card className="shadow-none"><CardContent className="!p-0">{alerts.length===0?<div className="py-16 text-center text-sm text-muted-foreground"><Bell className="mx-auto mb-4 size-7"/>알림이 없습니다.</div>:alerts.map(r=><div key={r.id} role="button" tabIndex={0} className="group flex gap-4 items-start p-5 border-b last:border-0 cursor-pointer hover:bg-muted/40" onClick={()=>{setRead(p=>[...new Set([...p,r.id])]);onOpen(r)}}><span className={`size-2 mt-2 rounded-full ${read.includes(r.id)?'bg-transparent':'bg-foreground'}`}/><div className="flex-1"><p className="text-sm">{r.owner}님에게 {r.kind}가 배정되었습니다.</p><div className="flex gap-2 mt-2"><span className="font-mono text-xs text-muted-foreground">{r.id}</span><PatternBadge pattern={r.pattern} probability={r.probability}/></div><p className="text-xs text-muted-foreground mt-2">{r.date} 13:38</p></div><DropdownMenu><DropdownMenuTrigger asChild><Button variant="ghost" size="icon" onClick={e=>e.stopPropagation()}><MoreHorizontal className="size-4"/></Button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem onClick={e=>{e.stopPropagation();setRead(p=>read.includes(r.id)?p.filter(x=>x!==r.id):[...p,r.id])}}>{read.includes(r.id)?'읽지 않음으로 처리':'읽음으로 처리'}</DropdownMenuItem><DropdownMenuItem onClick={e=>{e.stopPropagation();toast.info(`${r.id} · ${r.title}`)}}>요약 보기</DropdownMenuItem></DropdownMenuContent></DropdownMenu></div>)}</CardContent></Card></div>
}
